var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];g in c||(c[g]={});c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,e){$jscomp.initSymbolIterator();c=null!=c?c:function(a){return a};var b=[],d=a[Symbol.iterator];if("function"==typeof d){a=d.call(a);for(var f=0;!(d=a.next()).done;)b.push(c.call(e,d.value,f++))}else for(d=a.length,f=0;f<d;f++)b.push(c.call(e,a[f],f));return b}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var g=b.length,d=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var f=0;f<d&&c<g;)if(b[c++]!=a[f++])return!1;return f>=d}},"es6","es3");var browser=browser||chrome;
function getQuantity(){function a(a){a=(new DOMParser).parseFromString(a,"text/html");var b=Array.from(a.querySelectorAll("input[name]")).filter(function(a){return(a=a.getAttribute("name"))&&a.startsWith("n:")});if(b&&0<b.length&&b[0].value)a=b[0].value,console.log("retrieved quantity is: "+a),ispyconfig.offer.quantity=a,browser.runtime.sendMessage({action:"displayResults",source:{offers:[ispyconfig.offer]}});else if(b=a.querySelectorAll("div[data-asin]"),console.log("items length: "+b.length),0<
b.length){for(var c=[],d=0;d<b.length;d++){a=parseInt(b[d].getAttribute("data-quantity"));var f=b[d].getAttribute("data-encoded-offering"),k=/smid=([A-Z0-9]+)/.exec(b[d].innerHTML),h;k&&(h=k[1].replace(/"/g,""));c.push({offerId:f,quantity:a,merchantId:h});console.log("quanity: "+a+", merchantId: "+h)}browser.runtime.sendMessage({action:"displayResults",source:{offers:c}})}console.log("ispy cart cleared");setTimeout(clearCart,100)}var b=new URLSearchParams;b.append("a",ispyconfig.offer.asin);b.append("oid",
ispyconfig.offer.offerId);b.append("o","add");b.append("quantity","99999");b.append("verificationSessionID",ispyconfig.sessionId);console.log("ispyconfig: "+JSON.stringify(ispyconfig));fetch("/gp/aw/c/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"},body:b}).then(function(b){return b.text().then(function(b){console.log("send data");a(b)})})}
function clearCart(){fetch("/gp/cart/view.html?ref_=nav_cart",{method:"GET",headers:{"Content-Type":"application/x-www-form-urlencoded"}}).then(function(a){return a.text().then(function(a){a=(new DOMParser).parseFromString(a,"text/html");clearForm(a.getElementById("activeCartViewForm"));clearForm(a.getElementById("savedCartViewForm"))})})}
function clearForm(a){var b=new URLSearchParams;if(a&&0!=a.querySelectorAll("[data-action='delete']").length){var c=a.querySelectorAll("[data-action='delete']");console.log("found "+c.length+" action deletes.");for(var e=0;e<c.length;e++)b.append(c[e].name,"1"),b.append("requestID",a.elements.requestID.value),b.append("token",a.elements.token.value),b.append("timeStamp",a.elements.timeStamp.value),b.append("fromAUI","1"),b.append("pageAction","delete-active"),b.append("actionType","delete"),fetch("/cart/ref=ox_sc_cart_actions_1",
{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b}).then(function(a){return a.text().then(function(a){})})}else console.log("no cart items found")};
