var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,c={next:function(){if(d<a.length){var f=d++;return{value:b(f,a[f]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in d||(d[f]={});d=d[f]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var ph_host="https://rebelsoftwarellc.com",currentTab,key="",otherOpts={},myListener=null,requestId=0,workingOffers,domain,panicId,isFF=-1<navigator.userAgent.toLowerCase().indexOf("firefox"),browser=browser||chrome,panicLevel=0;console.log("miner.js loaded");browser.action.onClicked.addListener(function(a){currentTab=a;browser.storage.sync.get({otherOpts:""},function(b){b&&(otherOpts=b.otherOpts,actionClicked(a))})});
function actionClicked(a){console.log("actionclicked");0>a.url.indexOf("amazon")?browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert("Inventory Spy works only on an Amazon offer-listings page.")}}):-1<a.url.indexOf("dp")&&(discoverASIN(a.url)?browser.storage.sync.get({key:""},function(a){a&&(key=a.key);restrictAction()}):-1<a.url.indexOf("/cart/view.html")?clearCart():browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert("Please navigate to an offer-listings page on Amazon and try again.")}}))}
function clearCart(){chrome.scripting.executeScript({target:{tabId:currentTab.id},files:["lib/getQuantity.js"]},function(){chrome.scripting.executeScript({target:{tabId:currentTab.id},func:function(){"function"===typeof clearCart?clearCart():console.error("clearCart function is not defined")}})})}
function runAction(){finalResults={};shownTotals={};panicLevel=total=0;try{browser.action.disable(currentTab.id)}catch(a){console.log(a)}browser.scripting.insertCSS({target:{tabId:currentTab.id},files:["css/loading.css"]});browser.scripting.executeScript({target:{tabId:currentTab.id},files:["lib/returnMerchantListData.js"]})}
function restrictAction(){browser.storage.sync.get("clickmap",function(a){null==a&&(a={});clickmap=a.clickmap;null==clickmap&&(clickmap={});a=getTodayAsKey();null==clickmap[a]&&(clickmap={},clickmap[a]=0);clickmap[a]++;browser.storage.sync.set({clickmap:clickmap},function(){browser.extension.lastError&&console.log("An error occurred: "+browser.extension.lastError.message)});6>clickmap[a]?runAction():requestPurchase()})}
function getTodayAsKey(){var a=new Date,b=a.getDate(),d=a.getMonth();a=a.getFullYear();return d+1+"-"+b+"-"+a}
function sendObjecttoHost(a,b){fetch(a,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)}).then(function(a){if(!a.ok)throw Error("Network response was not ok "+a.statusText);return a.text()}).then(function(a){a&&(a=JSON.parse(a),a.error?("Usage Exceeded"==a.message?requestPurchase():browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert(a.message)}}),hideLoading()):(a.offers?(newFailures=[],displayResults(resp.offers,!1)):browser.scripting.executeScript({target:{tabId:currentTab.id},
func:function(){browser.runtime.sendMessage({action:"displayResults",source:{offers:[]}})}}),a.authorized&&browser.storage.sync.set({clickmap:null})))}).catch(function(a){hideLoading();console.log("error with server");browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert("We are sorry but the Inventory Spy Service is currently unavailable.  Please contact support@rebelsoftwarellc.com.")}});browser.storage.sync.set({clickmap:null})})}
function sendObjecttoHostOld(a,b){var d=null,c=new XMLHttpRequest;c.open("PUT",a,!0);c.setRequestHeader("Content-Type","application/json");c.onreadystatechange=function(){4==c.readyState&&(c.responseText||200<=c.status?c.responseText&&(d=JSON.parse(c.responseText),d.error?("Usage Exceeded"==d.message?requestPurchase():browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert("'+resp.message+'")}}),hideLoading()):(d.offers?(newFailures=[],displayResults(d.offers,!1)):retrieveQuantities(),
d.authorized&&browser.storage.sync.set({clickmap:null}))):(hideLoading(),console.log("error with server"),browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert("We are sorry but the Inventory Spy Service is currently unavailable.  Please contact support@rebelsoftwarellc.com.")}}),browser.storage.sync.set({clickmap:null})))};c.send(JSON.stringify(b))}
function hideLoading(){browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){document.getElementById("phLoadingDiv").setAttribute("class","hideLoading")}});try{browser.action.enable(currentTab.id)}catch(a){console.log(a)}}function domainHasTenRestriction(a){return!1}var newFailures=[],finalResults={},shownTotal={},total;
function displayResults(a,b){workingOffers=[];b||(a=a.reverse());for(var d=0;d<a.length;d++)null==a[d].quantity&&(2>panicLevel?(a[d].failretry=!1,newFailures.push(a[d])):a[d].quantity=0),domainHasTenRestriction(a[d].marketPlace)&&10==a[d].quantity&&!a[d].failretry&&(a[d].failretry=!1,newFailures.push(a[d])),null!=a[d].quantity&&!1!==a[d].failretry&&(finalResults[a[d].pageIndex]=parseInt(a[d].quantity),browser.scripting.executeScript({target:{tabId:currentTab.id},args:[a,d],func:function(a,b){if(null==
document.getElementById("ispy"+a[b].pageIndex)){var d=0==a[b].quantity||void 0==a[b].quantity?"(failed)":"("+a[b].quantity+" left",c=document.createElement("span");c.id="ispy"+a[b].pageIndex;c.innerHTML=d;document.querySelectorAll(".olpOffer, #aod-pinned-offer, #aod-offer")[a[b].pageIndex].querySelector(".olpOfferPrice, .a-price").appendChild(c)}}}));0<newFailures.length&&(resetPanic(),b=!0,a=newFailures.pop(),a.failretry=!0,workingOffers.push(a),retrieveSingleQuantity());b||(showTotals(),panicLevel=
0,hideLoading(),clearCart())}function showTotals(){var a=0,b=Object.keys(finalResults);b.sort(function(a,b){return a-b});b.forEach(function(b){var c="";otherOpts.showTotals&&(a+=finalResults[b]||0,0<b&&!shownTotal[b]&&(c=" : <i>"+a+" total</i>"));browser.scripting.executeScript({target:{tabId:currentTab.id},args:[b,c],func:function(a,b){document.getElementById("ispy"+a).innerHTML+=b+")"}})})}
function retrieveSingleQuantity(){"smile.amazon.com"==workingOffers[0].marketPlace&&(workingOffers[0].marketPlace="amazon.com");chrome.scripting.executeScript({target:{tabId:currentTab.id},func:function(a){window.ispyconfig=a},args:[{offer:workingOffers[0],sessionId:sessionId}]},function(){chrome.scripting.executeScript({target:{tabId:currentTab.id},files:["lib/getQuantity.js"]},function(){chrome.scripting.executeScript({target:{tabId:currentTab.id},func:function(){"function"===typeof getQuantity?
getQuantity():console.error("getQuantity function is not defined")}})})})}
function addQuantities(a,b){b=[];clearTimeout(panicId);var d=0;a:for(;d<a.length;d++){for(var c=0;c<workingOffers.length;c++)if((workingOffers[c].merchantName==a[d].merchantId||workingOffers[c].merchantId==a[d].merchantId||workingOffers[c].offerId==a[d].offerId)&&!workingOffers[c].quantity){workingOffers[c].quantity=a[d].quantity;continue a}console.log(a[d].merchantId+" was not found")}for(d=0;d<workingOffers.length;d++)workingOffers[d].quantity||b.push(workingOffers[d]);return{workingOffers:workingOffers,
failures:b}}
browser.runtime.onMessage.addListener(function(a,b){"ENABLE_ISPY"==a.action&&(b=getTodayAsKey(),clickmap[b]--,browser.storage.sync.set({clickmap:clickmap},function(){browser.extension.lastError&&console.log("An error occurred: "+browser.extension.lastError.message)}),hideLoading());"getData"==a.action?mineOfferListings(a.source):"abortRetrieval"==a.action?(newFailures=[],workingOffers=[],finalResults={},shownTotals={},panicLevel=total=0,hideLoading()):"displayResults"==a.action?(a=a.source.offers,b=
{},1==a.length&&a[0].failretry&&a[0].asin?(b.workingOffers=a,b.failures=[],clearTimeout(panicId)):b=addQuantities(a,workingOffers),workingOffers=b.workingOffers,b=b.failures,a=0<b.length,b.length!=workingOffers.length&&(b={},b.productKey=key,b.clientVersion=browser.runtime.getManifest().version,b.offers=workingOffers,b.offers=b.offers.reverse(),sendObjecttoHost(ph_host+"/service/logquantities",b)),a&&0==panicLevel&&(panicLevel=1),displayResults(workingOffers,a)):"resetpanic"==a.action?(console.log("panic timeout reset"),
resetPanic()):"buysubscription"==a.action?browser.tabs.create({url:"https://rebelsoftwarellc.com/inventoryspy/checkout",active:!0},function(a){}):"subscriptionpurchased"==a.action&&(browser.storage.sync.set({clickmap:null}),browser.storage.sync.set({key:a.source}),purchaseThankYou())});
function purchaseThankYou(){browser.storage.sync.get({lastAmzTabID:""},function(a){a=a.lastAmzTabID;browser.tabs.update(a,{selected:!0});browser.scripting.executeScript({target:{tabId:a},func:function(){alert("Thank you for your purchase! Inventory Spy Unlimited is now active.  Please retry your request.")}})})}
function requestPurchase(){browser.storage.sync.set({lastAmzTabID:currentTab.id});browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){alert("You have used your five clicks for today!  Please consider purchasing the Inventory Spy Unlimited subscription.");browser.runtime.sendMessage({action:"buysubscription"})}})}
function discoverASIN(a){var b=/dp\/([^?]+)/.exec(a),d=null;b?(b[1].split(/[?#]/),d=b[1].split(/[\/]/)[0]):(b=/B[0-9]{2}[0-9A-Z]{7}|[0-9]{9}(X|[0-9])/.exec(a))&&(d=b[0]);return d}
function mineOfferListings(a){if(a.results){sessionId=a.sessionId;var b=/(www.)*(.+)/.exec(a.domain);domain=b[2];for(var d=[],c=a.results,f=0;f<c.length;f++)if(0!=c[f].replace(/\s/g,"").length){c[f]=c[f].replaceAll("&quot;",'"');c[f]=c[f].replace(/>\s+</g,"><");var e={};e.marketPlace=domain;(b=/name="offeringID\.1" value="([^"]+)"/.exec(c[f]))&&0<b.length?(e.offerId=b[1],e.asin=a.asin):(b=/name="oid" value="([^"]+)"/.exec(c[f]))&&0<b.length?(e.offerId=b[1],e.asin=a.asin):(b=/"oid":"([^"]+)"/.exec(c[f]))&&
0<b.length&&(e.offerId=b[1],e.asin=a.asin);(b=/title="([^"]+)"/.exec(c[f]))&&0<b.length&&null!=b[1]&&0<b[1].trim().length?e.merchantName=b[1]:(b=/seller=([A-Z0-9]+)"/.exec(c[f]))&&0<b.length&&null!=b[1]&&0<b[1].trim().length?e.merchantName=b[1]:(b=/seller=.*">([^<]+)<\/a><\/span>/.exec(c[f]))&&0<b.length&&null!=b[1]&&0<b[1].trim().length?e.merchantName=b[1]:(b=/olpSellerName.*">([^<]+)<\/a><\/span>/.exec(c[f]))&&0<b.length&&null!=b[1]&&0<b[1].trim().length?e.merchantName=b[1]:(b=/shops\/([^/]+)\//.exec(c[f]))&&
1<b.length&&null!=b[1]?e.merchantName=b[1]:(b=/olpSellerName.*>([^<]+)<\/font><\/font><\/a>/.exec(c[f]))&&0<b.length&&null!=b[1]&&(e.merchantName=b[1]);(b=/[\$|\u00a3](\S+)\s*<\/span>/.exec(c[f]))&&0<b.length?e.price=b[1].replace(/,/g,""):(b=/\d{1,3}(?:[.,]\d{3})*(?:[.,]\d{2})/.exec(c[f]))&&0<b.length?e.price=b[0]:(b=/<span>Price not displayed/.exec(c[f]))&&0<b.length&&(e.price=-1);(b=/olpShippingPrice">[\$|\u00a3](\S+)<\/span>/.exec(c[f]))&&0<b.length&&(e.shippingPrice=b[1]);(b=/maxQty":(\d+),/.exec(c[f]))&&
0<b.length&&30!=b[1]&&(console.log("quantity: "+b[1]),e.quantity=b[1]);(b=/name="merchantID" value="([A-Z0-9]+)/.exec(c[f]))?e.merchantId=b[1]:(b=/seller=([A-Z0-9]+)/.exec(c[f]))?e.merchantId=b[1]:(b=/olp_merch_name.*?&amp;s=([A-Z0-9]+)\"/.exec(c[f]))?e.merchantId=b[1]:"amazon.com"==domain?e.merchantId="ATVPDKIKX0DER":"amazon.co.uk"==domain?e.merchantId="A3P5ROKL5A1OLE":"amazon.ca"==domain?e.merchantId="A3DWYIK6Y9EEQB":"amazon.de"==domain?e.merchantId="A3JWKAKR8XB7XF":"amazon.it"==domain?e.merchantId=
"A11IL2PNWYJU7H":"amazon.fr"==domain?e.merchantId="A1X6FK5RDHNB96":"amazon.es"==domain?e.merchantId="A1AT7YVPFBWXBL":"amazon.co.jp"==domain&&(e.merchantId="AN1VRQENFRJN5");e.pageIndex=f;e.fba=-1<c[f].indexOf("FREE Super Saver Shipping")||-1<c[f].indexOf("FREE Shipping")||-1<c[f].indexOf("isAmazonFulfilled=1");e.url=a.url;otherOpts.skipMyInventory&&e.merchantName.toLowerCase()==otherOpts.sellerName.toLowerCase()&&(e.quantity=0,e.failretry=!0,e.skipped=!0);e.offerId&&d.push(e)}workingOffers=d;workingOffers.reverse();
a={};a.productKey=key;a.clientVersion=browser.runtime.getManifest().version;sendObjecttoHost(ph_host+"/service/validateuser",a)}}
function resetPanic(){clearTimeout(panicId);0==panicLevel?panicId=setTimeout(function(){console.log("panic!");panicLevel++;browser.scripting.executeScript({target:{tabId:currentTab.id},func:function(){browser.runtime.sendMessage({action:"displayResults",source:{offers:[]}})}})},15E3):1==panicLevel&&(panicId=setTimeout(function(){console.log("panic!");panicLevel++;browser.runtime.getManifest();newFailures.push(workingOffers[0])},5E3))};
