'use strict';var k,aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");
for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}},l=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};da("globalThis",function(a){return a||ca});
da("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m=this||self,ea=function(a){var b=typeof a;b=b!="object"?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b=="object"&&typeof a.length=="number"},p=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"},fa=function(a,b,c){return a.call.apply(a.bind,arguments)},ha=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,
e)}}return function(){return a.apply(b,arguments)}},q=function(a,b,c){q=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?fa:ha;return q.apply(null,arguments)},r=function(a,b){function c(){}c.prototype=b.prototype;a.La=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ja=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};var u="getAccounts hello getLogBuffer recordLog getQuirks updateQuirks uiEvent proxyUIEvent getProxyConfig".split(" ");var oa=function(a){switch(a){case ia.name:return ia;case ja.name:return ja;case ka.name:return ka;case la.name:return la;case ma.name:return ma;default:let b=na.get(a);b||(b=new v(a),na.set(a,b));return b}},v=class{constructor(a){this.name=a}toString(){return this.name}},na=new Map,ia=new v("async"),ja=new v("generic"),ka=new v("runtime"),la=new v("system"),ma=new v("crypto"),pa=class extends Error{constructor(a,b,c){super(c);this.code=a;this.category=b;Object.setPrototypeOf(this,new.target.prototype)}toString(){return`${this.category}:${this.code} (${this.message||
"Undefined error."})`}};var qa=class{constructor(){let a=void 0,b=void 0;this.promise=new Promise((c,d)=>{a=c;b=d});this.resolve=a;this.reject=b}},ra=class extends pa{constructor(a,b="One or more errors occurred."){super(1,ia,b);this.errors=a;Object.setPrototypeOf(this,new.target.prototype)}flatten(){const a=[],b=[this.errors.slice(0)];for(;b.length!==0;){const c=b[0];for(;c.length!==0;){const d=c.shift();if(d instanceof ra){b.unshift(d.errors.slice(0));break}else a.push(d)}b[0]===c&&b.shift()}return new ra(a,this.message)}};var sa=class{constructor(){this.A=[]}subscribe(a){this.A.push(a)}unsubscribe(a){a=this.A.indexOf(a);if(a===-1)return!1;this.A.splice(a,1);return!0}publish(...a){const b=[],c=this.A.slice(0);for(const d of c)b.push(d(...a));return b}};function w(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{const c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}r(w,Error);w.prototype.name="CustomError";var ta;const ua=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},va=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){const c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function wa(a){const b=a.length;if(b>0){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]};var za=function(a){a:{var b=["window","location","href"];var c=m;for(var d=0;d<b.length;d++)if(c=c[b[d]],c==null){c=null;break a}}a==null&&(a='Unknown Error of type "null/undefined"');if(typeof a==="string")return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:c,stack:"Not available"};b=!1;try{var e=a.lineNumber||a.line||"Not available"}catch(g){e="Not available",b=!0}try{var f=a.fileName||a.filename||a.sourceURL||m.$googDebugFname||c}catch(g){f="Not available",b=!0}c=xa(a);return!b&&
a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name?{message:a.message,name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:c}:(b=a.message,b==null&&(b=a.constructor&&a.constructor instanceof Function?'Unknown Error of type "'+(a.constructor.name?a.constructor.name:ya(a.constructor))+'"':"Unknown Error of unknown type",typeof a.toString==="function"&&Object.prototype.toString!==a.toString&&(b+=": "+a.toString())),{message:b,name:a.name||"UnknownError",lineNumber:e,fileName:f,stack:c||"Not available"})},
xa=function(a,b){b||(b={});b[Aa(a)]=!0;var c=a.stack||"";(a=a.cause)&&!b[Aa(a)]&&(c+="\nCaused by: ",a.stack&&a.stack.indexOf(a.toString())==0||(c+=typeof a==="string"?a:a.message+"\n"),c+=xa(a,b));return c},Aa=function(a){var b="";typeof a.toString==="function"&&(b=""+a);return b+a.stack},Ba=function(a){var b=Error();if(Error.captureStackTrace)Error.captureStackTrace(b,a||Ba),b=String(b.stack);else{try{throw b;}catch(c){b=c}b=(b=b.stack)?String(b):null}b||(b=Ca(a||arguments.callee.caller,[]));return b},
Ca=function(a,b){var c=[];if(ua(b,a)>=0)c.push("[...circular reference...]");else if(a&&b.length<50){c.push(ya(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){e>0&&c.push(", ");var f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=ya(f))?f:"[fn]";break;default:f=typeof f}f.length>40&&(f=f.slice(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(Ca(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")},ya=function(a){if(x[a])return x[a];a=String(a);if(!x[a]){var b=/function\s+([^\(]+)/m.exec(a);x[a]=b?b[1]:"[Anonymous]"}return x[a]},x={};var y=function(){this.ra=Date.now()},Da=null;y.prototype.set=function(a){this.ra=a};y.prototype.reset=function(){this.set(Date.now())};y.prototype.get=function(){return this.ra};var z=class{constructor(a,b){this.name=a;this.value=b}toString(){return this.name}},A=new z("OFF",Infinity),Ea=new z("SHOUT",1200),Fa=new z("SEVERE",1E3),Ga=new z("WARNING",900),Ha=new z("INFO",800),Ia=new z("CONFIG",700),B=[A,Ea,Fa,Ga,Ha,Ia,new z("FINE",500),new z("FINER",400),new z("FINEST",300),new z("ALL",0)],C=null,Ja=class{constructor(){this.N=0;this.clear()}clear(){this.fa=Array(this.N);this.ia=-1;this.ka=!1}},Ka,La=class{constructor(a,b,c,d,e){this.I=void 0;this.reset(a||A,b,c,d,e)}reset(a,
b,c,d){this.wa=d||Date.now();this.aa=a;this.Ea=b;this.la=c;this.I=void 0}getMessage(){return this.Ea}},Ma=function(a){return a.level?a.level:a.parent?Ma(a.parent):A},Na=class{constructor(a,b=null){this.level=null;this.A=[];this.parent=b||null;this.children=[];this.Da={Z:()=>a}}publish(a){let b=this;for(;b;)b.A.forEach(c=>{c(a)}),b=b.parent}},D=function(a,b){var c=a.entries[b];if(c)return c;c=b.lastIndexOf(".");c=b.slice(0,Math.max(c,0));c=D(a,c);const d=new Na(b,c);a.entries[b]=d;c.children.push(d);
return d},Oa=class{constructor(){this.entries={};const a=new Na("");a.level=Ia;this.entries[""]=a}},Pa,E=function(){Pa||(Pa=new Oa);return Pa},Qa=function(a,b,c){var d;if(d=a)if(d=a&&b){d=b.value;var e=a?Ma(D(E(),a.Z())):A;d=d>=e.value}if(d){b=b||A;d=D(E(),a.Z());typeof c==="function"&&(c=c());Ka||(Ka=new Ja);e=Ka;a=a.Z();if(e.N>0){var f=(e.ia+1)%e.N;e.ia=f;e.ka?(e=e.fa[f],e.reset(b,c,a),a=e):(e.ka=f==e.N-1,a=e.fa[f]=new La(b,c,a))}else a=new La(b,c,a);a.I=void 0;d.publish(a)}},Sa=function(a){var b=
Ra;b&&Qa(b,Ha,a)};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function F(a){return a.toString().indexOf("`")===-1}F(a=>a``)||F(a=>a`\0`)||F(a=>a`\n`)||F(a=>a`\u0000`);var Ta=globalThis.trustedTypes;let Ua=Ta,Va;function Wa(){let a=null;if(!Ua)return a;try{const b=c=>c;a=Ua.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var G=class{constructor(a){this.na=a}toString(){return this.na+""}};function Xa(a){Va===void 0&&(Va=Wa());var b=Va;return new G(b?b.createHTML(a):a)}var Ya=new G(Ta?Ta.emptyHTML:"");function H(a){if(a instanceof G)return a.na;throw Error("");};var Za=class{constructor(a){this.oa=a}toString(){return this.oa}};function $a(a){return new Za(a[0])};var I=class{constructor(a){this.pa=a}toString(){return this.pa}},ab=new I("about:invalid#zClosurez");class bb{constructor(a){this.isValid=a}}function J(a){return new bb(b=>b.substr(0,a.length+1).toLowerCase()===a+":")}const cb=[J("data"),J("http"),J("https"),J("mailto"),J("ftp"),new bb(a=>/^[^:]*([/?#]|$)/.test(a))];function db(a,b=cb){if(a instanceof I)return a;for(let c=0;c<b.length;++c){const d=b[c];if(d instanceof bb&&d.isValid(a))return new I(a)}}var eb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function K(a,b={}){if(a instanceof G)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");b.F&&(a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;"));b.C&&(a=a.replace(/(\r\n|\n|\r)/g,"<br>"));b.Ka&&(a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>'));return Xa(a)}function L(a){const b=K("");return Xa(a.map(c=>H(K(c))).join(H(b).toString()))}const fb=/^[a-z][a-z\d-]*$/i,gb="APPLET BASE EMBED IFRAME LINK MATH META OBJECT SCRIPT STYLE SVG TEMPLATE".split(" ");
var hb="AREA BR COL COMMAND HR IMG INPUT KEYGEN PARAM SOURCE TRACK WBR".split(" ");const ib=["action","formaction","href"];function jb(a){if(!fb.test(a))throw Error("");if(gb.indexOf(a.toUpperCase())!==-1)throw Error("");}function M(a,b,c){jb(a);let d=`<${a}`;b&&(d+=kb(b));Array.isArray(c)||(c=c===void 0?[]:[c]);hb.indexOf(a.toUpperCase())!==-1?d+=">":(b=L(c.map(e=>e instanceof G?e:K(String(e)))),d+=">"+b.toString()+"</"+a+">");return Xa(d)}
function kb(a){var b="";const c=Object.keys(a);for(let f=0;f<c.length;f++){var d=c[f],e=a[d];if(!fb.test(d))throw Error("");if(e!==void 0&&e!==null){if(/^on./i.test(d))throw Error("");ib.indexOf(d.toLowerCase())!==-1&&(e instanceof I?e=e.toString():(e=String(e),e=eb.test(e)?e:void 0,e=e||"about:invalid#zClosurez"));d=`${d}="${K(String(e))}"`;b+=" "+d}}return b};"ARTICLE SECTION NAV ASIDE H1 H2 H3 H4 H5 H6 HEADER FOOTER ADDRESS P HR PRE BLOCKQUOTE OL UL LH LI DL DT DD FIGURE FIGCAPTION MAIN DIV EM STRONG SMALL S CITE Q DFN ABBR RUBY RB RT RTC RP DATA TIME CODE VAR SAMP KBD SUB SUP I B U MARK BDI BDO SPAN BR WBR NOBR INS DEL PICTURE PARAM TRACK MAP TABLE CAPTION COLGROUP COL TBODY THEAD TFOOT TR TD TH SELECT DATALIST OPTGROUP OPTION OUTPUT PROGRESS METER FIELDSET LEGEND DETAILS SUMMARY MENU DIALOG SLOT CANVAS FONT CENTER ACRONYM BASEFONT BIG DIR HGROUP STRIKE TT".split(" ").concat(["BUTTON",
"INPUT"]);var N=function(a){this.ma=a||"";Da||(Da=new y);this.ua=Da};k=N.prototype;k.ea=!0;k.S=!0;k.ca=!0;k.ta=!0;k.ba=!1;k.da=!1;
var lb=function(a){a=new Date(a.wa);return O(a.getFullYear()-2E3)+O(a.getMonth()+1)+O(a.getDate())+" "+O(a.getHours())+":"+O(a.getMinutes())+":"+O(a.getSeconds())+"."+O(Math.floor(a.getMilliseconds()/10))},O=function(a){return a<10?"0"+a:String(a)},mb=function(a,b){a=(a.wa-b)/1E3;b=a.toFixed(3);var c=0;if(a<1)c=2;else for(;a<100;)c++,a*=10;for(;c-- >0;)b=" "+b;return b},P=function(a){N.call(this,a)};r(P,N);P.prototype.ba=!0;P.prototype.ja=function(a){return a?this.X(a).toString():""};
P.prototype.X=function(a){if(!a)return Ya;switch(a.aa.value){case Ea.value:var b="dbg-sh";break;case Fa.value:b="dbg-sev";break;case Ga.value:b="dbg-w";break;case Ha.value:b="dbg-i";break;default:b="dbg-f"}var c=[];c.push(this.ma," ");this.S&&c.push("[",lb(a),"] ");this.ca&&c.push("[",mb(a,this.ua.get()),"s] ");this.ta&&c.push("[",a.la,"] ");this.da&&c.push("[",a.aa.name,"] ");c=K(c.join(""),{C:!0,F:!0});var d=Ya;if(this.ba&&a.I){d=M("br");try{var e=za(a.I);var f=e.fileName;f==null&&(f="");if(/^https?:\/\//i.test(f)){var g=
db(f,cb)||ab;if(g instanceof I)var h=g.pa;else throw Error("");var n=new I("view-source:"+h)}else n=db("sanitizedviewsrc",cb)||ab;var t=L([K("Message: "+e.message+"\nUrl: ",{C:!0,F:!0}),M("a",{href:n,target:"_new"},e.fileName),K("\nLine: "+e.lineNumber+"\n\nBrowser stack:\n"+e.stack+"-> [end]\n\nJS stack traversal:\n"+Ba(void 0)+"-> ",{C:!0,F:!0})])}catch(Vb){t=K("Exception trying to expose exception! You win, we lose. "+Vb,{C:!0,F:!0})}d=L([d,t])}a=K(a.getMessage(),{C:!0,F:!0});b=M("span",{"class":b},
L([a,d]));return this.ea?L([c,b,M("br")]):L([c,b])};var Q=function(a){N.call(this,a)};r(Q,N);Q.prototype.ja=function(a){var b=[];b.push(this.ma," ");this.S&&b.push("[",lb(a),"] ");this.ca&&b.push("[",mb(a,this.ua.get()),"s] ");this.ta&&b.push("[",a.la,"] ");this.da&&b.push("[",a.aa.name,"] ");b.push(a.getMessage());this.ba&&(a=a.I,a!==void 0&&b.push("\n",a instanceof Error?a.message:String(a)));this.ea&&b.push("\n");return b.join("")};Q.prototype.X=function(a){return K(Q.prototype.ja(a),{C:!0,F:!0})};function nb(a=new Q){a.S=!0;a.ca=!1;a.da=!0}function ob(a){a:{var b=a.l;if(!C){C={};for(let c=0,d;d=B[c];c++)C[d.value]=d,C[d.name]=d}if(b in C)b=C[b];else{for(let c=0;c<B.length;++c){let d=B[c];if(d.value<=b){b=d;break a}}b=null}}return new La(b,a.m,a.n,a.t,a.s)}D(E(),"");var pb=new z("TRACE",100);B.push(new z("DEBUG",600));B.push(pb);function qb(a,b,...c){return l(function*(){const d=new qa,e={magic:91556947316803,host:a!==null&&typeof a==="number"?"*":a,method:b,args:c},f=g=>{const h=chrome.runtime.lastError;h?d.reject(new pa(1,ka,`Operation '${String(b)}' failed. ${h.message||"Undefined error."}`)):g.error!==void 0?d.reject(rb(g.error)):d.resolve(g.result)};a!==null&&typeof a==="number"?chrome.tabs.sendMessage(a,e,f):chrome.runtime.sendMessage(e,f);return d.promise}())}
function rb(a){switch(a.type){case 0:return a.object;case 1:return Error(a.message);case 2:return new pa(a.code,oa(a.category),a.message);case 3:return new ra(a.errors.map(rb),a.message)}};var sb=function(a){for(const [c,d]of a.qa){const e=c;var b=d;if(u.every(f=>e.has(f)))return b}b={};for(const c of u)Object.defineProperty(b,c,{value:(...d)=>a.invoke(c,...d),writable:!1});a.qa.set(new Set(u),b);return b},tb=function(a){let b=a.events.get("log:record");if(!b){const c=chrome.runtime.connect({name:"log:record"}),d=new sa;b={port:c,source:d,Fa:[]};c.onMessage.addListener(e=>{e=Array.isArray(e)?e:[e];const f=b.Fa.shift();f?f.resolve(e.length>1?e:e[0]):d.publish(...e)});a.events.set("log:record",
b)}return b},ub=class{constructor(){this.host="*";this.events=new Map;this.qa=new Map}invoke(a,...b){const c=this;return l(function*(){return qb(c.host,a,...b)}())}};function vb(a,b){for(const c in a)b.call(void 0,a[c],c,a)};function wb(a){a=a.tagName;if(a==="SCRIPT"||a==="STYLE")throw Error("");};function R(){var a=m.navigator;return a&&(a=a.userAgent)?a:""}var S;const xb=m.navigator;S=xb?xb.userAgentData||null:null;function T(a){return R().indexOf(a)!=-1};function U(){return!!S&&!!S.platform}function yb(){return T("iPhone")&&!T("iPod")&&!T("iPad")};S&&S.brands.length>0||T("Opera");S&&S.brands.length>0||T("Trident")||T("MSIE");T("Edge");!T("Gecko")||R().toLowerCase().indexOf("webkit")!=-1&&!T("Edge")||T("Trident")||T("MSIE")||T("Edge");R().toLowerCase().indexOf("webkit")!=-1&&!T("Edge")&&T("Mobile");U()||T("Macintosh");U()||T("Windows");(U()?S.platform==="Linux":T("Linux"))||U()||T("CrOS");U()||T("Android");yb();T("iPad");T("iPod");yb()||T("iPad")||T("iPod");R().toLowerCase().indexOf("kaios");var Ab=function(a,b){vb(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:zb.hasOwnProperty(d)?a.setAttribute(zb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})},zb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Bb=function(a,
b,c,d){function e(h){h&&b.appendChild(typeof h==="string"?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];if(!ea(f)||p(f)&&f.nodeType>0)e(f);else{a:{if(f&&typeof f.length=="number"){if(p(f)){var g=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){g=typeof f.item=="function";break a}}g=!1}va(g?wa(f):f,e)}}},Cb=function(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)},Db=function(a){return a.nodeType==
9?a:a.ownerDocument||a.document},V=function(a){this.H=a||m.document||document};V.prototype.getElementsByTagName=function(a,b){return(b||this.H).getElementsByTagName(String(a))};var Eb=function(a,b){a=a.H;b=b&&b!="*"?String(b).toUpperCase():"";b=a.querySelectorAll&&a.querySelector&&b?a.querySelectorAll(b+""):a.getElementsByTagName(b||"*");return b};k=V.prototype;k.setProperties=Ab;
k.ha=function(a,b,c){var d=this.H,e=arguments,f=e[1],g=Cb(d,String(e[0]));f&&(typeof f==="string"?g.className=f:Array.isArray(f)?g.className=f.join(" "):Ab(g,f));e.length>2&&Bb(d,g,e,2);return g};k.createElement=function(a){return Cb(this.H,a)};k.createTextNode=function(a){return this.H.createTextNode(String(a))};k.appendChild=function(a,b){a.appendChild(b)};k.append=function(a,b){Bb(Db(a),a,arguments,1)};k.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
k.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};k.getChildren=function(a){return a.children!=void 0?a.children:Array.prototype.filter.call(a.childNodes,function(b){return b.nodeType==1})};k.isElement=function(a){return p(a)&&a.nodeType==1};
k.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var Fb=function(a){q(this.U,this);this.Y=new P;this.Y.S=!1;this.g=a;this.Aa=this.g.ownerDocument||this.g.document;this.za=new V(this.Aa);var b=$a`
      .dbg-sev{color:#F00}
      .dbg-w{color:#C40}
      .dbg-sh{font-weight:bold;color:#000}
      .dbg-i{color:#444}
      .dbg-f{color:#999}
      .dbg-ev{color:#0A0}
      .dbg-m{color:#990}
      .logmsg{border-bottom:1px solid #CCC;padding:2px}
      .logsep{background-color: #8C8;}
      .logdiv{border:1px solid #CCC;background-color:#FCFCFC;font:medium monospace}`;a=(a=this.g)?new V(Db(a)):ta||(ta=new V);var c=Eb(a,"HEAD")[0];if(!c){var d=Eb(a,"BODY")[0];c=a.ha("HEAD");d.parentNode.insertBefore(c,d)}d=a.ha("STYLE");var e;let f;const g=(f=(e=window.document).querySelector)==null?void 0:f.call(e,"style[nonce]");(e=g?g.nonce||g.getAttribute("nonce")||"":"")&&d.setAttribute("nonce",e);if(b instanceof Za)b=b.oa;else throw Error("");if(m.trustedTypes)if("textContent"in d)d.textContent=
b;else if(d.nodeType==3)d.data=String(b);else if(d.firstChild&&d.firstChild.nodeType==3){for(;d.lastChild!=d.firstChild;)d.removeChild(d.lastChild);d.firstChild.data=String(b)}else{for(;e=d.firstChild;)d.removeChild(e);d.appendChild(Db(d).createTextNode(String(b)))}else d.innerHTML=b;a.appendChild(c,d);this.g.className+=" logdiv"};
Fb.prototype.U=function(a){if(a){var b=this.g.scrollHeight-this.g.scrollTop-this.g.clientHeight<=100,c=this.za.createElement("DIV");c.className="logmsg";a=this.Y.X(a);c.nodeType===1&&wb(c);c.innerHTML=H(a);this.g.appendChild(c);b&&(this.g.scrollTop=this.g.scrollHeight)}};Fb.prototype.clear=function(){if(this.g){var a=this.g;a.nodeType===1&&wb(a);a.innerHTML=H(Ya)}};var Hb=class{constructor(){var a=Gb;this.xa=a;this.background=sb(a)}initialize(){const a=this;return l(function*(){const b=document.querySelector("#log-buffer"),c=new Fb(b);nb(c.Y);tb(a.xa).source.subscribe(e=>{const f=b.scrollTop===b.scrollHeight;c.U(ob(e));f&&(b.scrollTop=b.scrollHeight)});var d=yield a.background.getLogBuffer();for(const e of d)c.U(ob(e));if(d=document.querySelector("#clear-log"))d.onclick=()=>{c.clear()};d=document.querySelectorAll("[data-i18n]");for(const e of d)d=e.getAttribute("data-i18n"),
e.textContent=chrome.i18n.getMessage(d)||"PLACEHOLDER"}())}};class Ib{constructor(a,b){this.Ca=100;this.ya=a;this.Ga=b;this.R=0;this.P=null}get(){let a;this.R>0?(this.R--,a=this.P,this.P=a.next,a.next=null):a=this.ya();return a}put(a){this.Ga(a);this.R<this.Ca&&(this.R++,a.next=this.P,this.P=a)}};var Jb=function(){};var Kb,Lb=function(){var a=m.MessageChannel;typeof a==="undefined"&&typeof window!=="undefined"&&window.postMessage&&window.addEventListener&&!T("Presto")&&(a=function(){var e=Cb(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var g="callImmediate"+Math.random(),h=f.location.protocol=="file:"?"*":f.location.protocol+"//"+f.location.host;e=q(function(n){if((h=="*"||n.origin==h)&&n.data==g)this.port1.onmessage()},
this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if(typeof a!=="undefined"){var b=new a,c={},d=c;b.port1.onmessage=function(){if(c.next!==void 0){c=c.next;var e=c.ga;c.ga=null;e()}};return function(e){d.next={ga:e};d=d.next;b.port2.postMessage(0)}}return function(e){m.setTimeout(e,0)}};function Mb(a){m.setTimeout(()=>{throw a;},0)};class Nb{constructor(){this.T=this.G=null}add(a,b){const c=Ob.get();c.set(a,b);this.T?this.T.next=c:this.G=c;this.T=c}remove(){let a=null;this.G&&(a=this.G,this.G=this.G.next,this.G||(this.T=null),a.next=null);return a}}var Ob=new Ib(()=>new Pb,a=>a.reset());class Pb{constructor(){this.next=this.scope=this.fn=null}set(a,b){this.fn=a;this.scope=b;this.next=null}reset(){this.next=this.scope=this.fn=null}};let W,Qb=!1,Rb=new Nb,Tb=(a,b)=>{W||Sb();Qb||(W(),Qb=!0);Rb.add(a,b)},Sb=()=>{if(m.Promise&&m.Promise.resolve){const a=m.Promise.resolve(void 0);W=()=>{a.then(Ub)}}else W=()=>{var a=Ub;typeof m.setImmediate!=="function"||m.Window&&m.Window.prototype&&m.Window.prototype.setImmediate==m.setImmediate?(Kb||(Kb=Lb()),Kb(a)):m.setImmediate(a)}};var Ub=()=>{let a;for(;a=Rb.remove();){try{a.fn.call(a.scope)}catch(b){Mb(b)}Ob.put(a)}Qb=!1};var Y=function(a){this.i=0;this.sa=void 0;this.v=this.j=this.u=null;this.O=this.V=!1;if(a!=Jb)try{var b=this;a.call(void 0,function(c){X(b,2,c)},function(c){X(b,3,c)})}catch(c){X(this,3,c)}},Wb=function(){this.next=this.context=this.B=this.J=this.o=null;this.K=!1};Wb.prototype.reset=function(){this.context=this.B=this.J=this.o=null;this.K=!1};var Xb=new Ib(function(){return new Wb},function(a){a.reset()}),Yb=function(a,b,c){var d=Xb.get();d.J=a;d.B=b;d.context=c;return d};
Y.prototype.then=function(a,b,c){return Zb(this,typeof a==="function"?a:null,typeof b==="function"?b:null,c)};Y.prototype.$goog_Thenable=!0;Y.prototype.va=function(a,b){return Zb(this,null,a,b)};Y.prototype.catch=Y.prototype.va;Y.prototype.cancel=function(a){if(this.i==0){var b=new Z(a);Tb(function(){$b(this,b)},this)}};
var $b=function(a,b){if(a.i==0)if(a.u){var c=a.u;if(c.j){for(var d=0,e=null,f=null,g=c.j;g&&(g.K||(d++,g.o==a&&(e=g),!(e&&d>1)));g=g.next)e||(f=g);e&&(c.i==0&&d==1?$b(c,b):(f?(d=f,d.next==c.v&&(c.v=d),d.next=d.next.next):ac(c),bc(c,e,3,b)))}a.u=null}else X(a,3,b)},dc=function(a,b){a.j||a.i!=2&&a.i!=3||cc(a);a.v?a.v.next=b:a.j=b;a.v=b},Zb=function(a,b,c,d){var e=Yb(null,null,null);e.o=new Y(function(f,g){e.J=b?function(h){try{var n=b.call(d,h);f(n)}catch(t){g(t)}}:f;e.B=c?function(h){try{var n=c.call(d,
h);n===void 0&&h instanceof Z?g(h):f(n)}catch(t){g(t)}}:g});e.o.u=a;dc(a,e);return e.o};Y.prototype.Ha=function(a){this.i=0;X(this,2,a)};Y.prototype.Ia=function(a){this.i=0;X(this,3,a)};
var X=function(a,b,c){if(a.i==0){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.i=1;a:{var d=c,e=a.Ha,f=a.Ia;if(d instanceof Y){dc(d,Yb(e||Jb,f||null,a));var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(t){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{if(p(d))try{var n=d.then;if(typeof n==="function"){ec(d,n,e,f,a);g=!0;break a}}catch(t){f.call(a,t);g=!0;break a}g=!1}}}g||(a.sa=c,a.i=b,a.u=null,cc(a),b!=3||c instanceof Z||fc(a,c))}},ec=function(a,b,c,d,e){var f=!1,g=function(n){f||
(f=!0,c.call(e,n))},h=function(n){f||(f=!0,d.call(e,n))};try{b.call(a,g,h)}catch(n){h(n)}},cc=function(a){a.V||(a.V=!0,Tb(a.Ba,a))},ac=function(a){var b=null;a.j&&(b=a.j,a.j=b.next,b.next=null);a.j||(a.v=null);return b};Y.prototype.Ba=function(){for(var a;a=ac(this);)bc(this,a,this.i,this.sa);this.V=!1};
var bc=function(a,b,c,d){if(c==3&&b.B&&!b.K)for(;a&&a.O;a=a.u)a.O=!1;if(b.o)b.o.u=null,gc(b,c,d);else try{b.K?b.J.call(b.context):gc(b,c,d)}catch(e){hc.call(null,e)}Xb.put(b)},gc=function(a,b,c){b==2?a.J.call(a.context,c):a.B&&a.B.call(a.context,c)},fc=function(a,b){a.O=!0;Tb(function(){a.O&&hc.call(null,b)})},hc=Mb,Z=function(a){w.call(this,a)};r(Z,w);Z.prototype.name="cancel";var ic=function(a,b){if(typeof a!=="function")if(a&&typeof a.handleEvent=="function")a=q(a.handleEvent,a);else throw Error("Invalid listener argument");return Number(b)>2147483647?-1:m.setTimeout(a,b||0)},jc=function(a){let b=null;return(new Y(function(c,d){b=ic(function(){c(void 0)},a);b==-1&&d(Error("Failed to schedule timer."))})).va(function(c){m.clearTimeout(b);throw c;})};const Gb=new ub,kc=sb(Gb),Ra=D(E(),"Log Script").Da;function lc(){l(function*(){Sa("Initializing...");for(let b=1;b<=10;++b)try{yield kc.hello();break}catch(c){const d=c;if(b>=10){var a=Ra;a&&Qa(a,Fa,`Failed to communicate with background page after ${b} attempts. ${d.message}`);throw d;}yield jc(100+(15<<b))}yield(new Hb).initialize();Sa("Done.")}())}document.addEventListener("DOMContentLoaded",()=>{Sa("Handling DOMContentLoaded...");lc()});
